// <auto-generated />
using System;
using Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220829195521_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.BuildingElements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ContiguousSpaceId")
                        .HasColumnType("int");

                    b.Property<float>("EffectiveArea")
                        .HasColumnType("real");

                    b.Property<int>("EmbededIn")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpacesId")
                        .HasColumnType("int");

                    b.Property<float?>("ThermalResistance")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("SpacesId");

                    b.ToTable("BuildingElements");
                });

            modelBuilder.Entity("Domain.Entities.Layers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BuildingElementsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("ThermalConductivity")
                        .HasColumnType("real");

                    b.Property<float?>("ThermalResistance")
                        .HasColumnType("real");

                    b.Property<float?>("Thickness")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BuildingElementsId");

                    b.ToTable("Layers");
                });

            modelBuilder.Entity("Domain.Entities.Spaces", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreysId")
                        .HasColumnType("int");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("StoreysId");

                    b.ToTable("Spaces");
                });

            modelBuilder.Entity("Domain.Entities.SpaceTemperatures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("SpaceTemperatures");
                });

            modelBuilder.Entity("Domain.Entities.Storeys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Storeys");
                });

            modelBuilder.Entity("Domain.Entities.ThermalConductivityTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ThermalConductivityTables");
                });

            modelBuilder.Entity("Domain.Entities.ThermalResistanceTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ThermalResistanceTable");
                });

            modelBuilder.Entity("Domain.Entities.BuildingElements", b =>
                {
                    b.HasOne("Domain.Entities.Spaces", "Spaces")
                        .WithMany("BuildingElements")
                        .HasForeignKey("SpacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spaces");
                });

            modelBuilder.Entity("Domain.Entities.Layers", b =>
                {
                    b.HasOne("Domain.Entities.BuildingElements", "BuildingElements")
                        .WithMany("Layers")
                        .HasForeignKey("BuildingElementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingElements");
                });

            modelBuilder.Entity("Domain.Entities.Spaces", b =>
                {
                    b.HasOne("Domain.Entities.Storeys", "Storeys")
                        .WithMany("Spaces")
                        .HasForeignKey("StoreysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Storeys");
                });

            modelBuilder.Entity("Domain.Entities.BuildingElements", b =>
                {
                    b.Navigation("Layers");
                });

            modelBuilder.Entity("Domain.Entities.Spaces", b =>
                {
                    b.Navigation("BuildingElements");
                });

            modelBuilder.Entity("Domain.Entities.Storeys", b =>
                {
                    b.Navigation("Spaces");
                });
#pragma warning restore 612, 618
        }
    }
}
